export const LeveragedTokenAbi = [
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "baseAmount", type: "uint256" },
      { name: "minOut", type: "uint256" },
    ],
    outputs: [{ name: "ltAmount", type: "uint256" }],
  },
  {
    type: "function",
    name: "redeem",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "ltAmount", type: "uint256" },
      { name: "minBase", type: "uint256" },
    ],
    outputs: [{ name: "baseAmount", type: "uint256" }],
  },
  {
    type: "function",
    name: "baseAssetBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "exchangeRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "targetLeverage",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isLong",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "underlyingSymbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "baseToLtAmount",
    stateMutability: "view",
    inputs: [{ name: "baseAmount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "ltToBaseAmount",
    stateMutability: "view",
    inputs: [{ name: "ltAmount", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
