// This file is auto-generated by Ponder. Do not edit directly.
// Re-run `ponder codegen` to regenerate.
declare module "@/generated" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const ponder: any;
  export { ponder };
}
