/// <reference lib="webworker" />

import { keccak_256 } from "@noble/hashes/sha3";

/**
 * Vanity-suffix miner. Lives in a Web Worker so the keccak hot loop doesn't
 * block React renders. We start `navigator.hardwareConcurrency` of these per
 * launch and let them race — the first to find a salt whose predicted clone
 * address ends with `suffix` wins, the hook tears down the rest.
 *
 * Design notes:
 *   - We do *not* import viem. viem's keccak goes through `bytesToHex` /
 *     `hexToBytes` per call, which adds ~2x overhead. Raw `@noble/hashes`
 *     `keccak_256(Uint8Array)` is the tight loop.
 *   - We pre-compute the EIP-1167 init code hash once on init and cache the
 *     two scratch buffers (`mixBuf` for `mixSalt`, `predictBuf` for the
 *     CREATE2 hash). Per iteration we only overwrite the 32 salt bytes in
 *     `mixBuf` and the 32 mixedSalt bytes in `predictBuf`.
 *   - Salts are generated by counter-incrementing a random 32-byte seed.
 *     Workers stride by their `workerCount` so two workers never test the
 *     same salt. Cheaper than `crypto.getRandomValues()` per attempt.
 */

interface InitMessage {
  type: "init";
  implementation: `0x${string}`;
  bondingProxy: `0x${string}`;
  creator: `0x${string}`;
  suffix: string; // lowercase hex, e.g. "a1fa"
  workerIndex: number;
  workerCount: number;
}

interface StopMessage {
  type: "stop";
}

type WorkerInbound = InitMessage | StopMessage;

interface ProgressMessage {
  type: "progress";
  attempts: number;
}

interface FoundMessage {
  type: "found";
  salt: `0x${string}`;
  address: `0x${string}`;
  attempts: number;
}

export type WorkerOutbound = ProgressMessage | FoundMessage;

const HEX = "0123456789abcdef";

function bytesToHex(bytes: Uint8Array, start: number, end: number): string {
  let s = "";
  for (let i = start; i < end; i++) {
    const b = bytes[i];
    s += HEX[(b >> 4) & 0xf] + HEX[b & 0xf];
  }
  return s;
}

function hexToBytes20(hex: string): Uint8Array {
  // Strip "0x", pad/truncate to 40 chars (20 bytes).
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  const padded = clean.padStart(40, "0").slice(-40);
  const out = new Uint8Array(20);
  for (let i = 0; i < 20; i++) {
    out[i] = parseInt(padded.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

// EIP-1167 minimal-proxy *creation* code (OpenZeppelin v5 layout). Must
// stay in lockstep with `Bonding`'s `Clones.cloneDeterministic` — see the
// notes in `packages/shared/src/vanity.ts` for why the suffix is the
// longer 15-byte form `5af43d82803e903d91602b57fd5bf3` rather than the
// original spec's 9-byte `5af43d82803d3d82f3`.
const EIP1167_PREFIX_HEX = "3d602d80600a3d3981f3363d3d373d3d3d363d73";
const EIP1167_SUFFIX_HEX = "5af43d82803e903d91602b57fd5bf3";

function buildInitCode(implBytes: Uint8Array): Uint8Array {
  const prefix = hexToBytes20(`0x${EIP1167_PREFIX_HEX}`);
  const suffixBytes = new Uint8Array(EIP1167_SUFFIX_HEX.length / 2);
  for (let i = 0; i < suffixBytes.length; i++) {
    suffixBytes[i] = parseInt(
      EIP1167_SUFFIX_HEX.slice(i * 2, i * 2 + 2),
      16,
    );
  }
  const out = new Uint8Array(prefix.length + 20 + suffixBytes.length);
  out.set(prefix, 0);
  out.set(implBytes, prefix.length);
  out.set(suffixBytes, prefix.length + 20);
  return out;
}

let stopped = false;

self.addEventListener("message", (event: MessageEvent<WorkerInbound>) => {
  const msg = event.data;
  if (msg.type === "stop") {
    stopped = true;
    return;
  }
  if (msg.type !== "init") return;

  stopped = false;

  const implBytes = hexToBytes20(msg.implementation);
  const deployerBytes = hexToBytes20(msg.bondingProxy);
  const creatorBytes = hexToBytes20(msg.creator);
  const suffix = msg.suffix.toLowerCase();
  const suffixLen = suffix.length;

  const initCode = buildInitCode(implBytes);
  const initCodeHash = keccak_256(initCode); // 32 bytes, constant per impl

  // mixBuf = abi.encode(address creator, bytes32 userSalt)
  //        = 32 bytes (12 zeros + 20-byte addr) + 32 bytes salt
  const mixBuf = new Uint8Array(64);
  mixBuf.set(creatorBytes, 12); // bytes 0..11 stay zero (left-pad address to 32b)

  // predictBuf = 0xff ++ deployer (20b) ++ mixedSalt (32b) ++ initCodeHash (32b) = 85 bytes
  const predictBuf = new Uint8Array(85);
  predictBuf[0] = 0xff;
  predictBuf.set(deployerBytes, 1);
  predictBuf.set(initCodeHash, 1 + 20 + 32);

  // Random 32-byte starting salt. Each worker strides by workerCount so two
  // workers never test the same value. We treat the salt as a big number
  // and increment its low 8 bytes — collisions across workers are bounded
  // by `workerCount` differences in the starting seeds.
  const saltBuf = new Uint8Array(32);
  crypto.getRandomValues(saltBuf);
  // Mark the worker index in the lowest byte so concurrent workers never
  // produce identical salts even after wrap-around in the inner counter.
  saltBuf[31] = (saltBuf[31] & 0xfe) | (msg.workerIndex & 0x01);
  // Use the last 8 bytes as a counter for the inner loop.

  let attempts = 0;
  const PROGRESS_INTERVAL = 5000;

  // Stride: bump bytes 24..31 (uint64) by `workerCount` each iteration so we
  // explore disjoint salt subspaces. We keep this in plain JS numbers since
  // BigInt math is meaningfully slower in a hot loop and 2^53 attempts is
  // never going to happen.
  let counterLo = 0;
  const stride = Math.max(msg.workerCount, 1);

  while (!stopped) {
    // Write counter into bytes 28..31 (low 32 bits of the salt). High bits
    // come from the random seed and never change — that's our entropy.
    saltBuf[28] = (counterLo >>> 24) & 0xff;
    saltBuf[29] = (counterLo >>> 16) & 0xff;
    saltBuf[30] = (counterLo >>> 8) & 0xff;
    saltBuf[31] = counterLo & 0xff;

    // mixSalt: keccak256(abi.encode(creator, userSalt))
    mixBuf.set(saltBuf, 32);
    const mixed = keccak_256(mixBuf);

    // predictAddress: keccak256(0xff ++ deployer ++ mixed ++ initCodeHash)[12:]
    predictBuf.set(mixed, 1 + 20);
    const addrHash = keccak_256(predictBuf);

    // Suffix check on the last `suffixLen` hex chars of the address. The
    // address is the last 20 bytes (40 hex chars) of `addrHash` — we slice
    // from `addrHash` directly (cheaper than building the whole address
    // string every time).
    const sliceStart = 32 - Math.ceil(suffixLen / 2);
    const tail = bytesToHex(addrHash, sliceStart, 32);
    // tail length is even; suffix may be shorter than tail's significant chars.
    // Compare the trailing `suffixLen` chars.
    if (tail.endsWith(suffix)) {
      const fullAddr = `0x${bytesToHex(addrHash, 12, 32)}` as `0x${string}`;
      const fullSalt = `0x${bytesToHex(saltBuf, 0, 32)}` as `0x${string}`;
      const found: FoundMessage = {
        type: "found",
        salt: fullSalt,
        address: fullAddr,
        attempts: attempts + 1,
      };
      (self as DedicatedWorkerGlobalScope).postMessage(found);
      stopped = true;
      return;
    }

    attempts++;
    counterLo = (counterLo + stride) >>> 0;

    if (attempts % PROGRESS_INTERVAL === 0) {
      const progress: ProgressMessage = { type: "progress", attempts };
      (self as DedicatedWorkerGlobalScope).postMessage(progress);
    }
  }
});
