/// <reference lib="webworker" />

import { keccak_256 } from "@noble/hashes/sha3";

/**
 * Vanity-suffix miner. Lives in a Web Worker so the keccak hot loop doesn't
 * block React renders. The on-chain `Bonding._checkVanity` enforces a fixed
 * minimum (`VANITY_SUFFIX = "00000"`, 5 trailing hex zeros). This worker
 * mines for the minimum first, then continues running and only re-emits a
 * `found` when it beats its own previous best — i.e. it keeps pushing for
 * progressively rarer addresses (6 zeros, 7 zeros, …) for as long as the
 * host lets it run. The host broadcasts `bumpTarget` whenever any sibling
 * worker finds a better salt so the whole pool stays in lockstep.
 *
 * Design notes:
 *   - We do *not* import viem. viem's keccak goes through `bytesToHex` /
 *     `hexToBytes` per call, which adds ~2x overhead. Raw `@noble/hashes`
 *     `keccak_256(Uint8Array)` is the tight loop.
 *   - We pre-compute the EIP-1167 init code hash once on init and cache
 *     the two scratch buffers (`mixBuf` for `mixSalt`, `predictBuf` for
 *     the CREATE2 hash). Per iteration we only overwrite the 32 salt
 *     bytes in `mixBuf` and the 32 mixedSalt bytes in `predictBuf`.
 *   - Salts are generated by counter-incrementing a random 32-byte seed.
 *     Workers stride by their `workerCount` so two workers never test the
 *     same salt. Cheaper than `crypto.getRandomValues()` per attempt.
 *   - Mining runs in chunks (`runMiner`), yielding to the worker task
 *     queue between chunks so inbound `bumpTarget` / `stop` messages can
 *     actually drain. A naive `while (!stopped)` blocks the worker event
 *     loop indefinitely and silently breaks the cross-worker lockstep
 *     protocol.
 */

interface InitMessage {
  type: "init";
  implementation: `0x${string}`;
  bondingProxy: `0x${string}`;
  creator: `0x${string}`;
  /**
   * `keccak256(bytes(name))` of the user-entered token name. Pre-hashed by
   * the host so the hot loop only ever moves fixed-size 32-byte words —
   * matches `Bonding._mixSalt`'s `keccak256(bytes(name_))`.
   */
  nameHash: `0x${string}`;
  /** `keccak256(bytes(ticker))` of the user-entered ticker. */
  tickerHash: `0x${string}`;
  /**
   * Initial trailing-zero target. The hot loop will fire `found` for any
   * address whose hex tail has at least this many trailing zeros, then
   * bump locally to `actualZeros + 1`. The host re-broadcasts the new
   * target via `bumpTarget` so sibling workers don't waste cycles
   * rediscovering an already-beaten threshold.
   */
  initialTargetZeros: number;
  workerIndex: number;
  workerCount: number;
}

interface StopMessage {
  type: "stop";
}

interface BumpTargetMessage {
  type: "bumpTarget";
  /** New minimum trailing-zero count. Worker only raises, never lowers. */
  targetZeros: number;
}

type WorkerInbound = InitMessage | StopMessage | BumpTargetMessage;

/**
 * Periodic progress tick. `attemptsDelta` is the number of attempts this
 * worker has tried since its previous `progress` message — *never* a
 * cumulative count.
 */
interface ProgressMessage {
  type: "progress";
  attemptsDelta: number;
}

/**
 * Winner notification. `zeros` is the actual trailing-zero count of the
 * predicted address (always ≥ the worker's current target). `attemptsDelta`
 * covers attempts since this worker's last progress tick.
 */
interface FoundMessage {
  type: "found";
  salt: `0x${string}`;
  address: `0x${string}`;
  zeros: number;
  attemptsDelta: number;
}

export type WorkerOutbound = ProgressMessage | FoundMessage;

const HEX = "0123456789abcdef";

function bytesToHex(bytes: Uint8Array, start: number, end: number): string {
  let s = "";
  for (let i = start; i < end; i++) {
    const b = bytes[i];
    s += HEX[(b >> 4) & 0xf] + HEX[b & 0xf];
  }
  return s;
}

/**
 * Strict hex → bytes decoder. Requires `expectedBytes * 2` hex chars after
 * the optional `0x` prefix and rejects anything outside `[0-9a-fA-F]`.
 *
 * The strictness matters: `parseInt(badPair, 16)` returns `NaN`, which
 * coerces to `0` when written into a `Uint8Array`. Without validation the
 * worker would silently mine against (e.g.) the wrong `nameHash` and burn
 * CPU until the salt eventually got rejected on-chain. Throwing here turns
 * any upstream serialisation bug into the worker's `error` event.
 */
function hexToBytes(hex: string, expectedBytes: number, label: string): Uint8Array {
  const clean = hex.startsWith("0x") || hex.startsWith("0X") ? hex.slice(2) : hex;
  const expectedChars = expectedBytes * 2;
  if (clean.length !== expectedChars) {
    throw new Error(
      `vanity.worker: ${label} must be ${expectedChars} hex chars (got ${clean.length})`,
    );
  }
  if (!/^[0-9a-fA-F]+$/.test(clean)) {
    throw new Error(`vanity.worker: ${label} contains non-hex characters`);
  }
  const out = new Uint8Array(expectedBytes);
  for (let i = 0; i < expectedBytes; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function hexToBytes20(hex: string, label: string): Uint8Array {
  return hexToBytes(hex, 20, label);
}

function hexToBytes32(hex: string, label: string): Uint8Array {
  return hexToBytes(hex, 32, label);
}

const EIP1167_PREFIX_HEX = "3d602d80600a3d3981f3363d3d373d3d3d363d73";
const EIP1167_SUFFIX_HEX = "5af43d82803e903d91602b57fd5bf3";

function buildInitCode(implBytes: Uint8Array): Uint8Array {
  const prefix = hexToBytes20(`0x${EIP1167_PREFIX_HEX}`, "EIP1167 prefix");
  const suffixBytes = new Uint8Array(EIP1167_SUFFIX_HEX.length / 2);
  for (let i = 0; i < suffixBytes.length; i++) {
    suffixBytes[i] = parseInt(
      EIP1167_SUFFIX_HEX.slice(i * 2, i * 2 + 2),
      16,
    );
  }
  const out = new Uint8Array(prefix.length + 20 + suffixBytes.length);
  out.set(prefix, 0);
  out.set(implBytes, prefix.length);
  out.set(suffixBytes, prefix.length + 20);
  return out;
}

/**
 * Count trailing `0` hex chars in the predicted-address tail of a
 * keccak-256 hash output. `addrHash` is the 32-byte CREATE2 hash; the
 * address is the last 20 bytes (40 hex chars). We scan right-to-left over
 * those 40 chars and stop at the first non-zero nibble. Capped at 40 (the
 * full address). Inlined manually rather than via `bytesToHex` + string
 * scan to avoid the per-attempt allocation.
 */
function countAddressTrailingZeros(addrHash: Uint8Array): number {
  let zeros = 0;
  for (let i = 31; i >= 12; i--) {
    const b = addrHash[i];
    const lo = b & 0xf;
    if (lo !== 0) return zeros;
    zeros++;
    const hi = (b >> 4) & 0xf;
    if (hi !== 0) return zeros;
    zeros++;
  }
  return zeros;
}

let stopped = false;
// Mutable across the worker's lifetime. `init` resets it; `bumpTarget` and
// in-loop self-bumps only ever raise it. Sentinel `Infinity` before init.
let targetZeros = Number.POSITIVE_INFINITY;
// Re-entrancy guard. The host always `terminate()`s a worker before
// re-spawning, so in practice a second `init` never arrives mid-run.
// This guard exists purely to make a misuse safe: a duplicate `init`
// while the loop is still draining is silently dropped (the state the
// running loop reads is captured in its `MinerState` argument and
// can't be hot-swapped from the message handler). If we ever need
// in-flight reconfiguration, that's a deliberate design change, not
// something to fall into accidentally.
let mining = false;

/** Iterations between yields. Sized so wall-clock per chunk is large
 *  relative to the yield cost (~0.1ms via the MessageChannel trick),
 *  keeping overhead under 1% while still bounding `bumpTarget` / `stop`
 *  latency to ~10-20ms on a typical multi-core machine (~3M attempts/sec).
 *  Also doubles as the progress-report cadence — at 50k attempts and
 *  6 workers, the host receives ~360 progress events/sec, which keeps the
 *  attempt counter smooth without flooding the UI thread. */
const CHUNK_SIZE = 50000;

/**
 * Yield to the worker's task queue so pending messages (`bumpTarget`,
 * `stop`) drain. `setTimeout(0)` would work but the HTML spec mandates
 * a 4ms minimum after 5 nested calls — at 3M attempts/sec that turns the
 * mining loop into a 30%+ idle time waste. The `MessageChannel` trick
 * sidesteps that clamp: posting a message to a same-thread port queues a
 * macrotask with no minimum delay, so the yield costs ~0.1ms.
 */
const yieldChannel = new MessageChannel();
function yieldToTaskQueue(): Promise<void> {
  return new Promise<void>((resolve) => {
    yieldChannel.port1.onmessage = () => resolve();
    yieldChannel.port2.postMessage(null);
  });
}

self.addEventListener("message", (event: MessageEvent<WorkerInbound>) => {
  const msg = event.data;
  if (msg.type === "stop") {
    stopped = true;
    return;
  }
  if (msg.type === "bumpTarget") {
    if (msg.targetZeros > targetZeros) {
      targetZeros = msg.targetZeros;
    }
    return;
  }
  if (msg.type !== "init") return;

  stopped = false;
  targetZeros = msg.initialTargetZeros;

  const implBytes = hexToBytes20(msg.implementation, "implementation");
  const deployerBytes = hexToBytes20(msg.bondingProxy, "bondingProxy");
  const creatorBytes = hexToBytes20(msg.creator, "creator");
  const nameHashBytes = hexToBytes32(msg.nameHash, "nameHash");
  const tickerHashBytes = hexToBytes32(msg.tickerHash, "tickerHash");

  const initCode = buildInitCode(implBytes);
  const initCodeHash = keccak_256(initCode);

  const mixBuf = new Uint8Array(128);
  mixBuf.set(creatorBytes, 12);
  mixBuf.set(nameHashBytes, 32);
  mixBuf.set(tickerHashBytes, 64);

  const predictBuf = new Uint8Array(85);
  predictBuf[0] = 0xff;
  predictBuf.set(deployerBytes, 1);
  predictBuf.set(initCodeHash, 1 + 20 + 32);

  const saltBuf = new Uint8Array(32);
  crypto.getRandomValues(saltBuf);

  if (mining) return;
  mining = true;
  void runMiner({
    mixBuf,
    predictBuf,
    saltBuf,
    counterLo: msg.workerIndex >>> 0,
    stride: Math.max(msg.workerCount, 1),
  }).finally(() => {
    mining = false;
  });
});

interface MinerState {
  mixBuf: Uint8Array;
  predictBuf: Uint8Array;
  saltBuf: Uint8Array;
  counterLo: number;
  stride: number;
}

/**
 * Mining loop, restructured into chunks that yield to the worker event
 * loop between iterations.
 *
 * Why chunked rather than a tight `while`: the worker's message handler
 * can only run when the JS execution context is idle. A tight synchronous
 * loop blocks all incoming messages (including `bumpTarget` and `stop`),
 * which silently broke the lockstep target-bump protocol — sibling
 * workers' bumps never reached this worker until termination.
 *
 * Two counters intentionally track different things:
 *   - `iterationsInChunk` controls when we yield. Always increments per
 *     attempt. Bounds the worst-case bumpTarget/stop latency to
 *     `CHUNK_SIZE` iterations regardless of how many `found` events fire
 *     mid-chunk (which reset the progress counter).
 *   - `attemptsSinceProgress` accumulates progress deltas the host hasn't
 *     seen yet. Resets on `found` (folded into the `attemptsDelta` of the
 *     `FoundMessage`) and on each progress emission so the host's
 *     attempt counter never double-counts.
 */
async function runMiner(state: MinerState): Promise<void> {
  let { counterLo } = state;
  const { stride, mixBuf, predictBuf, saltBuf } = state;

  while (!stopped) {
    let iterationsInChunk = 0;
    let attemptsSinceProgress = 0;

    while (!stopped && iterationsInChunk < CHUNK_SIZE) {
      saltBuf[28] = (counterLo >>> 24) & 0xff;
      saltBuf[29] = (counterLo >>> 16) & 0xff;
      saltBuf[30] = (counterLo >>> 8) & 0xff;
      saltBuf[31] = counterLo & 0xff;

      mixBuf.set(saltBuf, 96);
      const mixed = keccak_256(mixBuf);

      predictBuf.set(mixed, 1 + 20);
      const addrHash = keccak_256(predictBuf);

      const actualZeros = countAddressTrailingZeros(addrHash);

      if (actualZeros >= targetZeros) {
        const fullAddr = `0x${bytesToHex(addrHash, 12, 32)}` as `0x${string}`;
        const fullSalt = `0x${bytesToHex(saltBuf, 0, 32)}` as `0x${string}`;
        const found: FoundMessage = {
          type: "found",
          salt: fullSalt,
          address: fullAddr,
          zeros: actualZeros,
          // +1 for the winning attempt itself, on top of whatever's
          // accumulated since the host's last progress tick.
          attemptsDelta: attemptsSinceProgress + 1,
        };
        (self as DedicatedWorkerGlobalScope).postMessage(found);
        attemptsSinceProgress = 0;
        // Self-bump locally so we don't immediately re-emit at the same
        // threshold while the host's `bumpTarget` broadcast is in flight.
        targetZeros = actualZeros + 1;
      } else {
        attemptsSinceProgress++;
      }

      iterationsInChunk++;
      counterLo = (counterLo + stride) >>> 0;
    }

    // Drain partial chunk's progress before yielding so the host's
    // attempt counter stays smooth. Skip the post if a `found` on the
    // last iteration already drained the buffer to zero.
    if (attemptsSinceProgress > 0) {
      const progress: ProgressMessage = {
        type: "progress",
        attemptsDelta: attemptsSinceProgress,
      };
      (self as DedicatedWorkerGlobalScope).postMessage(progress);
    }

    if (stopped) return;

    // Yield. Pending `bumpTarget` / `stop` messages drain here.
    await yieldToTaskQueue();
  }
}
