version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      major:
        update-types: ["major"]
    open-pull-requests-limit: 5
